version: "3.9"
services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_USER: frontier
      POSTGRES_PASSWORD: frontier
      POSTGRES_DB: frontier
    ports: [ "5432:5432" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frontier -d frontier"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: [ "6379:6379" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
