[package]
name = "frontier-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
rust_decimal = { version = "1.35", features = ["serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
thiserror = "1.0"
